language: node_js
node_js:
 - "11.15.0"

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master

branches:
  except:
  - gp-pages
    
